// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpense(ctx context.Context, id int) error
	GetExpensesByUserID(ctx context.Context, userID int) ([]Expense, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error
}

var _ Querier = (*Queries)(nil)
